spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 102030

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 278675020158-vdi7801oiqatsuihjh6ts6ukiteuopgs.apps.googleusercontent.com
            client-secret: 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
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
